- internal/app/metal-metadata-server/main.go
This PR will fix a bug where we were overwriting the kubelet extra args
any time the node-labels key didn't exist.
> fix: ensure we don't clobber extraargs

- README.md
This fixes some lint errors, and allows long lines and inline HTML.
> docs: address markdown lint errors

- internal/app/metal-controller-manager/config/crd/kustomization.yaml
This PR goes ahead and adds the proper label that we'll need for our
server, serverclass, and environment CRDs in order for us to pivot them
to a target cluster using `clusterctl move`.
> chore: add move label to metal controller manager CRDs

- .dockerignore
- Dockerfile
- templates/cluster-template.yaml
This PR adds the necessary bits to publish a cluster-template for
sidero. This means users will now be able to gen a cluster yaml with `clusterctl config cluster test -i sidero`
Will close https://github.com/talos-systems/cluster-api-provider-metal/issues/16
> feat: add cluster-template for sidero

- docs/website/content/docs/bootstrapping.md
- internal/app/cluster-api-provider-sidero/controllers/metalmachine_controller.go
- templates/cluster-template.yaml
This PR adds an additional check to make sure the server we're picking
for a metalmachine isn't already in use. It also moves to using patches
for updating the in-use field. There's also a small doc update and a fix
to the cluster-template that was incorrect.
Will close #28
> fix: ensure servers only get picked once

- docs/website/content/docs/bootstrapping.md
This PR adds a full guide for the initial bootstrap and pivot flow.
We'll chase this with some guides around post-pivot and creation of our
first cluster from the management plane.
> docs: add full bootstrapping guide

- docs/website/content/docs/bootstrapping.md
This PR adds a very simple clarification that the templated manifest is
just a starting point and customizations should be added as needed.
> docs: add note about templated cluster manifest

- docs/website/content/docs/bootstrapping.md
- docs/website/content/docs/first-cluster.md
- docs/website/content/docs/patching.md
- docs/website/gridsome.config.js
This PR adds a guide for what comes after the initial bootsrap and
pivot. I think I've got some other ideas on how this can get a bit
easier over time. I'll create a new PR with that later.
Will close #42 #43
> docs: add a post-pivot/create first workload cluster guide

- app/cluster-api-provider-sidero/config/default/kustomization.yaml
- app/metal-controller-manager/config/kustomization.yaml
- app/metal-metadata-server/config/kustomization.yaml
- config/namespace.yaml
- docs/website/content/docs/bootstrapping.md
- docs/website/content/docs/first-cluster.md
This PR reverts commit f850aa348732510b742ace5e3ea923ee68cb1b73.
The change of namespace led to unexpected behavior with upstream
clusterctl and would cause confusion for end users.
> fix: revert "update namespace to caps-system"

- app/metal-controller-manager/api/v1alpha1/server_types.go
- app/metal-controller-manager/api/v1alpha1/server_types_test.go
- app/metal-controller-manager/controllers/serverclass_controller.go
Instead of requiring a complete match of qualifiers, we now support the ability
to do partial matching. This means users can omit fiels in the CPU and System
Information qualifiers, and it will be a valid qualifier. Prior to this, every
field had to match.
> feat: allow qualifers to be partially equal

- app/metal-metadata-server/main.go
This PR adds a bunch of additional logging for the metadata server. This
is an attempt to make it clearer when we can't lookup a server or
bootstrap data for any given reason.
Will close #59 
> chore: add additional logging for metadata server

- app/metal-controller-manager/api/v1alpha1/server_types.go
- app/metal-controller-manager/api/v1alpha1/server_types_test.go
This fixes a panic when comparing structs that are pointers.
> fix: address panic in PartialEqual

- app/metal-metadata-server/main.go
This PR fixes a bug where users could have orphaned metalmachines that still
had ownerrefs to a server that had alredy been made available for another
cluster. This led to incorrect metadata being returned. We now bail and
error early if we encounter multiple ownerrefs in the list pointing to
the same server.
> fix: ensure proper checking of "in-use" status when fetching metadata

- app/metal-metadata-server/main.go
This way (if context is used consistently) operation will be aborted
when client closes the connection.
> fix: use proper context in metadata server

- app/metal-controller-manager/internal/tftp/tftp_server.go
Prevents file descriptor leak.
> fix: close file in TFTP handler

- sfyra/pkg/tests/reset.go
We should ensure that the server ref is not nil.
> test: fix nil pointer panic

- Makefile
- hack/scripts/generate-clusterctl-config.sh
- hack/scripts/integration-test.sh
- sfyra/cmd/sfyra/main.go
- sfyra/cmd/sfyra/options.go
- sfyra/pkg/bootstrap/cluster.go
- sfyra/pkg/capi/capi.go
This makes sure automation won't overwrite the default config location.
> test: use dedicated config for the sfyra tests

- sfyra/pkg/capi/cluster.go
- sfyra/pkg/tests/management_cluster.go
This type implements `talos.Cluster` interface and allows to "look" at
the CAPI-provisioned cluster same way as Talos bootstrap cluster.
This is a first step to towards pivoting.
> test: extract `capi.Cluster` implementation

- app/metal-controller-manager/internal/server/server.go
It makes more sense to treat every newly added server as dirty so that we can
ensure it goes through the reset process.
> feat: set servers as dirty by default

- app/cluster-api-provider-sidero/controllers/metalmachine_controller.go
- app/metal-controller-manager/controllers/server_controller.go
We need to be certain that servers are clean before they are eligible for
use. This ensures that servers are put through the reset process before they
become ready.
> feat: ensure servers are clean

- Dockerfile
- app/metal-controller-manager/controllers/server_controller.go
- sfyra/pkg/tests/match.go
- sfyra/pkg/tests/tests.go
Basically this repeats the power off action which should be done by the
agent image. In case of Sfyra and QEMU VMs, they can't be shutdown via
ACPI, so this code is going to bring Sfyra case closer to the bare metal
case, plus it should handle power off if Server is registered manually
(without agent).
Also mark servers which are `InUse && !IsClean` as `Ready` to assert
that all the servers are ready in the test.
> feat: power down servers !InUse && IsClean

- sfyra/pkg/tests/reset.go
This PR will ensure that the machine is deleted by looking for the owner
of the metalmachine and deleting that instead of the metalmachine so
it'll cascade down.
> fix: delete machine instead of metalmachine in reset test

- app/metal-controller-manager/main.go
This PR adds erroring around the case where we can't start one of the
servers in metal controller manager. This will solve the case where port
conflicts are in use and exiting if so.
> fix: error when port conflicts happen

- Dockerfile
> fix: add ipmitool to metal-controller-manager

- sfyra/pkg/capi/metalclient.go
- sfyra/pkg/constants/constants.go
- sfyra/pkg/tests/environment.go
- sfyra/pkg/tests/server.go
- sfyra/pkg/tests/server_class.go
This PR moves the serverClass creation into a function that can be
called by multiple tests. Additionally, I added in a function to create
dummy servers that aren't backed by QEMU VMs. Helpful as we develop the
configPatching tests.
> test: break serverclass creation into function and allow dummy servers

- sfyra/pkg/tests/environment.go
- sfyra/pkg/tests/server.go
This makes `Shutdown()` API halt the QEMU machine instead of rebooting
it.
See https://github.com/talos-systems/talos/pull/2618
> test: apply talos.shutdown=halt kernel argument

- app/cluster-api-provider-sidero/controllers/metalmachine_controller.go
- app/metal-controller-manager/api/v1alpha1/server_types.go
- app/metal-controller-manager/config/crd/bases/metal.sidero.dev_servers.yaml
- app/metal-controller-manager/controllers/server_controller.go
- app/metal-controller-manager/controllers/serverclass_controller.go
- app/metal-controller-manager/internal/server/server.go
- app/metal-controller-manager/main.go
- sfyra/pkg/capi/capi.go
- sfyra/pkg/tests/server.go
- sfyra/pkg/tests/tests.go
This PR adds a bool field to the server spec of `accepted`. This allows
users to adopt a server that has been registered into the sidero
environment. Doing so allows for a server's full lifecycle to be
managed. Users can either edit a server resource to update the accepted
field, or create the server resource manually and supply that with their
spec.
The PR also adds some edge case handling around the sidero API server to
check to make sure a server is accepted before allowing a wipe directive
to be returned, as well as a check for acceptance when trying to use a
serverref in the sidero capi provider.
Will close #122
> feat: support server acceptance

- app/cluster-api-provider-sidero/controllers/metalcluster_controller.go
- app/cluster-api-provider-sidero/pkg/constants/constants.go
Looks like there's only a single place where it makes sense to change
`return err` to `RequeueAfter` in `metalcluster_controller`.
> chore: introduce RequeueAfter in metalcluster controller

- Dockerfile
This left around an unformatted file after `make generate`.
> chore: fix formatting

- app/metal-controller-manager/api/v1alpha1/server_types.go
- app/metal-controller-manager/config/crd/bases/metal.sidero.dev_servers.yaml
- app/metal-controller-manager/internal/server/server.go
Hostname was sent by the agent over gRPC, but not used.
Fixes #117
> feat: add hostname to the server spec

- sfyra/cmd/sfyra/cmd/loadbalancer_create.go
- sfyra/pkg/loadbalancer/loadbalancer.go
- sfyra/pkg/tests/management_cluster.go
The one which runs in the tests is still not verbose as it makes it hard
to see the test output.
> test: enable verbose logs for CLI version of loadbalancer

- Makefile
- sfyra/cmd/sfyra/cmd/options.go
It should fix test hangs on stopping PXE VMs.
> test: bump Talos to 0.7.0-alpha.6 for Sfyra

- sfyra/cmd/sfyra/cmd/test_integration.go
Adds the ability for overriding the initramfs , vmlinuz, and install image.
> test: add flags for modifying workload cluster images

- go.mod
- go.sum
- internal/pkg/ipmi/ipmi.go
- sfyra/go.sum
This ensures that EFI machines will be set to PXE boot and next boot.
> fix: use efiboot option

- sfyra/pkg/capi/capi.go
- sfyra/pkg/tests/reset.go
- sfyra/pkg/tests/server.go
- sfyra/pkg/tests/tests.go
When a server is dirty and not accepted, it should be reset after being accepted.
> test: check if servers are reset on acceptance

- app/metal-controller-manager/controllers/server_controller.go
- app/metal-controller-manager/main.go
As ServerController is a bit not following the best practices, as it
reconciles based on Status, we need to have it up to date.
> fix: use APIReader in server controller to avoid caching issues

- docs/website/content/docs/servers.md
Explains the `accepted` field of a `Server`.
> docs: add server acceptance note

- sfyra/go.mod
- sfyra/go.sum
- sfyra/pkg/loadbalancer/loadbalancer.go
This contains fixes for stalled connections to the stoppped VMs,
connections are now aborted quickly and controllers don't hit the bug
with Kubernetes client, HTTP/2 and idle connections.
> test: pull in the new version of go-loadbalancer

- app/metal-controller-manager/cmd/agent/main.go
Adds an exception for CDs, DVDs, and Blue-ray disks.
> fix: don't reset read only disks

- sfyra/pkg/tests/management_cluster.go
- sfyra/pkg/tests/server_class.go
- templates/cluster-template.yaml
We were missing support for tweaking the load balancer port
> chore: add support for control plane port

- app/metal-controller-manager/cmd/agent/main.go
- app/metal-controller-manager/internal/ipxe/ipxe_server.go
- go.mod
- go.sum
- sfyra/go.sum
This also fixes skipping of CD-ROM devices and other devices we can't
wipe for obvious reasons.
Based on https://github.com/talos-systems/go-blockdevice/pull/7
> fix: wipe disk fully in the agent

- docs/website/content/docs/v0.1/Getting Started/introduction.md
This PR adds some extra text to the overview about the inherent
chicken/egg problem with bootstrapping sidero.
Will close #164
> docs: add chicken and egg note to overview

- docs/website/content/docs/v0.1/Getting Started/concepts.md
This PR addresses an issue where it wasn't clear what "environments"
actually look like, for example. There are now links from the concept
section that prompt the user to head over to "Configuration" for
examples and detail on each concept.
Will close #168
> docs: add links between concepts and configuration sections

- docs/website/content/docs/v0.1/Guides/first-cluster.md
Revise the example DHCP config to handle BIOS-based PXE clients.
> docs: add non-UEFI clause to PXE example

- docs/website/content/docs/v0.1/Configuration/servers.md
Expand the Server acceptance documentation to better describe the
intention and function.
This addresses but does not completely resolve #177.  Additional
lifecycle documentation (which does not seem to appropriate here)
should be added to describe how to take a `Server` out of commission.
> docs: expand server acceptance doc

- docs/website/content/docs/v0.1/Configuration/metadata.md
This adds some text to the Metadata section, briefly describing the
Metadata server and the construction of the Talos configuration.
> docs: add a metadata section

- CHANGELOG.md
This is the official v0.1.0-alpha.7 release.
> release(v0.1.0-alpha.7): prepare release

- .drone.yml
- Dockerfile
- Makefile
- docs/website/content/docs/v0.1/Guides/patching.md
- hack/scripts/integration-test.sh
We need to move to ghcr.io because docker.io is now rate limiting pulls.
> chore: move to ghcr.io

- .drone.yml
We need to supply the registry to the `docker login` command.
> chore: fix docker login

- CHANGELOG.md
This is the official v0.1.0-alpha.8 release.
> release(v0.1.0-alpha.8): prepare release

- app/metal-controller-manager/cmd/agent/main.go
We can't reset a blockdevice if it doesn't have a partition table.
> fix: ignore missing partition error

- CHANGELOG.md
This is the official v0.1.0-alpha.9 release.
> release(v0.1.0-alpha.9): prepare release

- app/metal-controller-manager/cmd/agent/main.go
- app/metal-controller-manager/main.go
- go.mod
- go.sum
- sfyra/go.sum
Use new feature of go-blockdevice to implement the "fast wipe" in Sidero
and make it default one: https://github.com/talos-systems/go-blockdevice/pull/13
This new fast wipe is as good as zeroing out with most modern SSDs, but
not as secure, so we can call it "insecure wipe", but make it default to
improve the customer experience.
Fixes #207
> feat: make "insecure-wipe" default, use new fast wipe method

- app/metal-controller-manager/cmd/agent/main.go
This disables machine power off in discovery agent.
If `Server` resource has `IPMI` information, it will be powered off by
the Sidero controller once it's clean and accepted.
This simplifies the flow for non-IPMI environments, as machines are now
sitting in the boot loop and might start provisioning as soon as
`Server` is allocated.
Fixes #204
> feat: don't power off the server in discovery agent

- app/metal-controller-manager/api/v1alpha1/server_types.go
- app/metal-controller-manager/controllers/server_controller.go
- app/metal-controller-manager/pkg/constants/constants.go
It is helpful to know what the server's current power status is. This adds a field
to the server status indicating the current state.
> feat: add power status to servers

- app/cluster-api-provider-sidero/controllers/metalmachine_controller.go
This PR just adds a little output to the user that we couldn't find any
available servers in a serverclass. Helps troubleshoot that they may
have incorrect qualifiers or forgot to accept servers.
> chore: add info log when no servers in serverclass

- Makefile
- app/metal-controller-manager/config/crd/bases/metal.sidero.dev_servers.yaml
- go.mod
- go.sum
- sfyra/go.mod
- sfyra/go.sum
- sfyra/pkg/bootstrap/cluster.go
- sfyra/pkg/vm/set.go
This is mostly no changes, but as `pkg/provision` interface got changed
slightly, there are some fixups in Sfyra.
Also looks like power PR didn't have the CRD definition checked in.
Fixes #213
> chore: bump Talos package dependency to 0.7-beta.1

- app/metal-controller-manager/internal/ipxe/ipxe_server.go
- app/metal-controller-manager/main.go
This adds a `--extra-agent-kernel-args` flag to the metal controller manager that
allows for adding extra kernel parameters to the agent environment.
> feat: allow for extra kernel args in agent environment

- app/cluster-api-provider-sidero/controllers/metalmachine_controller.go
- app/metal-controller-manager/api/v1alpha1/server_types.go
- app/metal-controller-manager/config/crd/bases/metal.sidero.dev_servers.yaml
- app/metal-controller-manager/controllers/server_controller.go
- app/metal-controller-manager/controllers/serverclass_controller.go
- app/metal-controller-manager/internal/ipxe/ipxe_server.go
- app/metal-controller-manager/internal/server/server.go
- go.mod
Fixes #205
This change makes sure that server gets booted into the environment only
once (unless `.Spec.PXEBootAlways` is set).
If IPMI is used, there're no functional changes, as servers are supposed
to be configured to boot from disk first, and Sidero forces boot from
network as needed.
Without IPMI, now it's possible to set server to boot from network all
the time, and once provisioned, server will boot from disk.
> feat: boot servers via PXE only once by default

- docs/website/content/docs/v0.1/Guides/bootstrapping.md
We changed the names of these files in 0.7 Talos.
> docs: fix typo in asset URLs

- CHANGELOG.md
This is the official v0.1.0-alpha.12 release.
> release(v0.1.0-alpha.12): prepare release

- app/cluster-api-provider-sidero/config/crd/bases/infrastructure.cluster.x-k8s.io_serverbindings.yaml
- sfyra/pkg/capi/cluster.go
- sfyra/pkg/tests/cluster_utils.go
- sfyra/pkg/tests/management_cluster.go
- sfyra/pkg/tests/server_class.go
- sfyra/pkg/tests/tests.go
- sfyra/pkg/tests/workload_cluster.go
This cluster has a single controlplane node just for the sake of testing
with another cluster in place.
> test: add a test to deploy and destroy workload cluster

- templates/cluster-template.yaml
Minor nit to change the default pod and service subnets to align with Talos.
> feat: align default subnets with Talos

- docs/website/content/docs/v0.1/Guides/bootstrapping.md
This PR addresses some support issues we've seen where the `-xxx` part
of fetching a talosconfig is unclear. Moved to using the cluster label
to fetch the first talosconfig resource that matches.
Closes #238.
> docs: clarify process of fetching talosconfig

- docs/website/content/docs/v0.1/Guides/bootstrapping.md
- docs/website/content/docs/v0.1/Guides/first-cluster.md
Adds notes on what the cluster template environment variables are for.
> docs: clarify cluster template environment variables

- Dockerfile
- Makefile
This follows same model as we use in Talos build.
> chore: bump versions of packages used in the build

- docs/website/content/docs/v0.1/Guides/bootstrapping.md
We should have a note in the prerequisites about the need to install talos
before going through the bootstrapping guide.
Fixes: https://github.com/talos-systems/sidero/issues/192
> docs: describe the command to install talosctl in the bootstrap guide

- docs/website/content/docs/v0.1/Configuration/serverclasses.md
`labelSelector` key code block was a bit off.
> docs: fix typo on Server Classes page

- sfyra/pkg/tests/reconcile.go
- sfyra/pkg/tests/scale.go
Now that the control plane provider is in better shape, we can start testing.
> test: enable control plane scale down test

- app/metal-controller-manager/controllers/server_controller.go
- sfyra/pkg/tests/server_class.go
Fixes: https://github.com/talos-systems/sidero/issues/155
Introduce server finalizers, which will block server deletion until
server is deallocated.
> fix: prevent server orphaning

- docs/website/content/docs/v0.1/Configuration/servers.md
Adds documentation on how to specify an install disk.
> docs: add note on installation disk

- templates/cluster-template.yaml
This fixes an issue where the kubelet version for workers could be
subject to being older b/c of constants in the bootstrap provider. This
ensures that the kube version is the same between the control plane and
the worker machine deployment.
> fix: add kubernetes version to cluster template

- app/metal-controller-manager/internal/ipxe/ipxe_server.go
- docs/website/content/docs/v0.1/Guides/bootstrapping.md
- docs/website/content/docs/v0.1/Guides/first-cluster.md
This should allow pulling `ipxe.efi` using http protocol.
Fixes: https://github.com/talos-systems/sidero/issues/241
> feat: serve assets from TFTP folder in IPXE HTTP server

- app/metal-controller-manager/cmd/agent/main.go
This makes it clear to the user that an error is occurring in a retry
loop.
> fix: log retry errors

- .drone.yml
This should have no effect on regular builds, but for the release PR
build, tag for the upcoming build will be created local to the build so
that it exposes any versioning issues.
> chore: use common 'setup-ci' function

- sfyra/cmd/sfyra/cmd/options.go
- sfyra/cmd/sfyra/cmd/test_integration.go
- sfyra/pkg/tests/server.go
- sfyra/pkg/tests/tests.go
See https://github.com/talos-systems/cluster-api-bootstrap-provider-talos/issues/58
This makes sure tests are closer to real life: Talos version should be
driven by the `Environment` and installer image defaults.
> test: drop installer image from the server patch

- app/metal-controller-manager/controllers/serverclass_controller.go
As list of server names (UUIDs) was not sorted, and listing and
filtering servers is not deterministic, so on each ServerClass reconcile
ServerClass might be changed which triggers another reconcile and so on
until list of server UUIDs on two reconciles stays the same.
> fix: break the potential endless reconcile loop of ServerClasses

- Dockerfile
- Makefile
- app/cluster-api-provider-sidero/api/v1alpha2/metalmachinetemplate_types.go
- app/cluster-api-provider-sidero/api/v1alpha3/metalmachinetemplate_types.go
- app/cluster-api-provider-sidero/config/crd/bases/infrastructure.cluster.x-k8s.io_metalclusters.yaml
- app/cluster-api-provider-sidero/config/crd/bases/infrastructure.cluster.x-k8s.io_metalmachines.yaml
- app/cluster-api-provider-sidero/config/crd/bases/infrastructure.cluster.x-k8s.io_metalmachinetemplates.yaml
- app/cluster-api-provider-sidero/config/crd/bases/infrastructure.cluster.x-k8s.io_serverbindings.yaml
- app/metal-controller-manager/config/crd/bases/metal.sidero.dev_environments.yaml
- app/metal-controller-manager/config/crd/bases/metal.sidero.dev_serverclasses.yaml
- app/metal-controller-manager/config/crd/bases/metal.sidero.dev_servers.yaml
- app/metal-controller-manager/internal/api/api.pb.go
This bumps versions of build tools where possible, uses cache for Go
build, linting and modules extensively.
Not all the tools and features were bumped yet, so consider this part
one of N.
> chore: improve build system

- app/metal-controller-manager/cmd/agent/main.go
- go.mod
- go.sum
- sfyra/go.sum
See https://github.com/talos-systems/go-smbios/pull/8
This pulls also other changes from `go-smbios` which add new memory
information, but they're not used yet.
> feat: pull in new version of go-smbios for UUID endiannes fix

- app/metal-controller-manager/controllers/environment_controller.go
With that extra `wg.Add` controller was hanging forever on `wg.Wait()`
every time URL was changed.
> fix: remove erroneous wg.Add in environment controller

- docs/website/content/docs/v0.2/Guides/upgrades.md
- docs/website/content/docs/v0.3/Guides/upgrades.md
This PR points to existing Talos upgrade docs and details the cert
migration for v0.8 -> v0.9 of Talos
> docs: add guide for upgrades

- app/cluster-api-provider-sidero/config/manager/manager.yaml
- app/cluster-api-provider-sidero/main.go
- app/metal-controller-manager/config/manager/manager.yaml
- app/metal-controller-manager/config/manager_auth_proxy_patch.yaml
- app/metal-controller-manager/main.go
- app/metal-metadata-server/config/server/server.yaml
- docs/website/content/docs/v0.3/Getting Started/installation.md
- docs/website/content/docs/v0.3/Getting Started/resources.md
- docs/website/content/docs/v0.3/Guides/bootstrapping.md
- docs/website/content/docs/v0.3/Guides/first-cluster.md
- sfyra/pkg/capi/capi.go
This allows to skip patching any components on initial install, and if
the variables are preserved, settings are preserved across upgrades.
> feat: pull the Sidero configuration as `clusterctl` variables

- .github/dependabot.yml
- .gitignore
Just like we do in Talos.
After this PR is merged, dependabot should be enabled at https://github.com/talos-systems/sidero/settings/security_analysis
> chore: add dependabot config

- .drone.yml
- Makefile
The old output was interpreted as
--buildkitd-flags '--use'
that did not work.
Also fix .drone.yml signature.
> chore: fix `make help` command

- Dockerfile
- Makefile
- app/metal-controller-manager/internal/ipxe/ipxe_server.go
- app/metal-controller-manager/internal/ipxe/patch.go
- docs/website/content/docs/v0.3/Guides/bootstrapping.md
- docs/website/content/docs/v0.3/Guides/first-cluster.md
- sfyra/pkg/bootstrap/cluster.go
- sfyra/pkg/vm/set.go
Fixes #227
See also https://github.com/talos-systems/pkgs/pull/267
The rough idea is that iPXE binaries we're building contain placeholder
script which is replaced on the fly with the actual script which depends
on Sidero API endpoint. Patching is a bit tricky for `undionly.kpxe`, as
it is compressed, so we patch uncompressed version and compress the
final asset after that.
> feat: embed iPXE script into the iPXE binaries

- docs/website/content/docs/v0.1/Configuration/servers.md
- docs/website/content/docs/v0.2/Configuration/servers.md
- docs/website/content/docs/v0.3/Configuration/servers.md
We should always use raw devices.
> docs: fix install disk name in the examples

- docs/website/content/docs/v0.3/Guides/bootstrapping.md
- sfyra/pkg/tests/environment.go
This fixes part of the UEFI boot in Sfyra. UEFI boot is still buggy as
UEFI doesn't quite support forcing boot from the network via QEMU args,
but this brings it one step closer.
Also clarify in the docs that iPXE filename depends on the node
architecture.
> test: fix the Environment args to support UEFI boot

- app/cluster-api-provider-sidero/config/manager/manager.yaml
- app/metal-controller-manager/config/manager/manager.yaml
- app/metal-metadata-server/config/server/server.yaml
This fixes an issue where sidero can't be installed on a 2 CPU/2GB RAM
node. Backing down the requests so that the pods can get scheduled, but
still keeping the limits high.
> fix: back down resource requests

- sfyra/cmd/sfyra/cmd/options.go
After we scaled down requests fro our componenets, we can provision
smaller bootstrap node where CAPI gets installed.
> chore: cut bootstrap server resources in Sfyra

- docs/website/content/docs/v0.3/Configuration/environments.md
- docs/website/content/docs/v0.3/Configuration/metadata.md
- docs/website/content/docs/v0.3/Getting Started/installation.md
- docs/website/content/docs/v0.3/Getting Started/introduction.md
Bump references to Talos, remove explicit `Metadata Server` component as
it got merged into `metal-controller-manager`.
> docs: clarify docs around endpoints and metadata server

- app/metal-controller-manager/api/v1alpha1/serverclass_filter.go
- app/metal-controller-manager/api/v1alpha1/serverclass_filter_test.go
- app/metal-controller-manager/api/v1alpha1/serverclass_types.go
- app/metal-controller-manager/api/v1alpha1/zz_generated.deepcopy.go
- app/metal-controller-manager/config/crd/bases/metal.sidero.dev_serverclasses.yaml
- app/metal-controller-manager/config/samples/metal_v1alpha1_server.yaml
- app/metal-controller-manager/config/samples/metal_v1alpha1_serverclass.yaml
- app/metal-controller-manager/controllers/serverclass_controller.go
- website/content/docs/v0.3/Configuration/serverclasses.md
- website/content/docs/v0.3/Configuration/servers.md
Adds field `selector` to the root of the ServerClassSpec.
This implements the same schema/logic for selecting Servers as is
used in several builtin Kubernetes APIs.
Tests have been added to show the behavior when both `selector` and
`qualifiers` are used, as well as when neither are used.
https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/label-selector/
Signed-off-by: bzub <bzubrod@gmail.com>
Closes #282
> feat: add label selector to serverclass

- app/metal-controller-manager/config/crd/bases/metal.sidero.dev_serverclasses.yaml
Looks like wrong version was pushed leading to `-dirty` version.
> chore: fix generated CRDs

- .drone.yml
- Makefile
Prevents PRs which have some files not regenerated properly.
> chore: check for dirtiness of the source tree

- app/metal-controller-manager/api/v1alpha1/serverclass_types.go
- app/metal-controller-manager/config/crd/bases/metal.sidero.dev_serverclasses.yaml
As we actually don't require any of them to be set, mark them as
optional.
This fixes upgrade path from Sidero 0.2 to 0.3.
> fix: make server class qualifiers and selectors optional

- website/content/docs/v0.3/Guides/rpi4-as-servers.md
- website/content/docs/v0.3/Guides/upgrades.md
This guide explains how to use RPI4 as servers when using sidero.
Closes: https://github.com/talos-systems/talos/issues/3621
Signed-off-by: Kevin Hellemun <17928966+OGKevin@users.noreply.github.com>
> docs: add doc for using rpi4 as server.

- Makefile
- app/sidero-controller-manager/config/samples/metal_v1alpha1_environment.yaml
- go.mod
- go.sum
- sfyra/go.mod
- sfyra/go.sum
- website/content/docs/v0.3/Configuration/environments.md
This updates to the latest stable Talos release before cutting Sidero
0.3 final release.
> feat: update default Talos version to v0.10.3

- Dockerfile
This enforces arch properly for amd64/arm64 initramfs image for each of
the architecture.
This fixes a bug when Sidero on arm64 can't properly provision IPMI user
on amd64 box.
> fix: make sure components of agent environment are of proper arch

- website/content/docs/v0.2/Guides/iso.md
- website/content/docs/v0.3/Guides/iso.md
This PR documents the usage of the ISO for mgmt plane. It's mostly just
a note that it can be done and providing links to how to use the ISO and
then back to the Getting Started tutorial.
> docs: document using ISO for mgmt plane

- go.mod
- go.sum
- sfyra/go.mod
- sfyra/go.sum
This updates cabpt to v0.2.0 and cacppt to v0.1.0
> chore: update to latest stable talos providers

- CHANGELOG.md
- hack/release.toml
This is the official v0.3.0 release. I additionally added a note about iDRAC in the section about auto BMC setup.
> release(v0.3.0): prepare release

- sfyra/cmd/sfyra/cmd/bootstrap_capi.go
- sfyra/cmd/sfyra/cmd/options.go
- sfyra/cmd/sfyra/cmd/test_integration.go
- sfyra/pkg/capi/capi.go
This fixes a problem that our providers are not v1alpha4 ready yet.
> fix: update Sfyra to install CAPI v0.3

- website/content/docs/v0.2/Getting Started/create-workload.md
- website/content/docs/v0.2/Getting Started/expose-services.md
- website/content/docs/v0.2/Getting Started/import-machines.md
- website/content/docs/v0.2/Getting Started/index.md
- website/content/docs/v0.2/Getting Started/install-clusterapi.md
- website/content/docs/v0.2/Getting Started/pivot.md
- website/content/docs/v0.2/Getting Started/prereq-cli-tools.md
- website/content/docs/v0.2/Getting Started/prereq-dhcp.md
- website/content/docs/v0.2/Getting Started/prereq-kubernetes.md
- website/content/docs/v0.2/Getting Started/scale-workload.md
- website/content/docs/v0.2/Getting Started/troubleshooting.md
- website/content/docs/v0.3/Getting Started/create-workload.md
- website/content/docs/v0.3/Getting Started/expose-services.md
- website/content/docs/v0.3/Getting Started/import-machines.md
- website/content/docs/v0.3/Getting Started/index.md
- website/content/docs/v0.3/Getting Started/install-clusterapi.md
- website/content/docs/v0.3/Getting Started/pivot.md
- website/content/docs/v0.3/Getting Started/prereq-cli-tools.md
- website/content/docs/v0.3/Getting Started/prereq-dhcp.md
- website/content/docs/v0.3/Getting Started/prereq-kubernetes.md
- website/content/docs/v0.3/Getting Started/scale-workload.md
- website/content/docs/v0.3/Getting Started/troubleshooting.md
We should put H1 title to the metadata section of the document.
> docs: fix duplicate titles in the guides

- app/sidero-controller-manager/controllers/server_controller.go
We rely on the timestamp of the `PowerCycle` condition to be updated
properly when Sidero reboots the node (assuming previous attempt to PXE
boot failed). Looks like nothing we did before actually ensures that the
condition gets properly updated, so a little hack modifying condition
message to make sure actual condition gets patched properly with last
transition time.
> fix: make sure powercycle condition gets properly updated

- Makefile
- go.mod
- go.sum
- sfyra/go.mod
- sfyra/go.sum
More of a testcase for pkg/machinery tags.
> chore: bump Talos to 0.11.0-beta.3

- website/static/_redirects
This PR updates the redirect rules for making sure latest actually, you
know, points to the latest.
> docs: redirect latest to v0.3

- website/content/docs/v0.3/Getting Started/prereq-cli-tools.md
Fix incompatible API version:
```
Error: installing provider "bootstrap-talos" can lead to a non functioning management cluster: the target version for the provider supports the v1alpha3 API Version of Cluster API (contract), while the management group is using v1alpha4
```
Related Cluster API documentation: https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#note-on-user-experience
Signed-off-by: Khue Doan <khuedoan98@gmail.com>
> docs: bump clusterctl from v0.3.14 to v0.3.21 in /docs/website

- app/sidero-controller-manager/cmd/agent/main.go
This PR makes sure that the sidero user gets the `callin=true` access.
Setting this for these sidero users seems to function just fine on tests of both
iDrac and ASROCK BMCs.
> fix: update sidero IPMI user to work properly on idrac

- app/sidero-controller-manager/cmd/agent/main.go
- sfyra/cmd/sfyra/cmd/bootstrap_capi.go
- sfyra/cmd/sfyra/cmd/options.go
- sfyra/cmd/sfyra/cmd/test_integration.go
- sfyra/pkg/capi/capi.go
This PR backports the following fixes:
- fix: update Sfyra to install CAPI v0.3 [commit here](ea3016f)
- fix: update sidero IPMI user to work properly on idrac [commit here](7bdee0f)
> fix: backport fixes

- website/content/docs/v0.3/Guides/iso.md
- website/content/docs/v0.3/Guides/patching.md
- website/content/docs/v0.3/Guides/rpi4-as-servers.md
- website/content/docs/v0.3/Guides/sidero-on-rpi4.md
- website/content/docs/v0.3/Guides/upgrades.md
- website/content/docs/v0.3/Resource Configuration/environments.md
- website/content/docs/v0.3/Resource Configuration/metadata.md
- website/content/docs/v0.3/Resource Configuration/serverclasses.md
update: Talos v0.11 docs
Fix ServerClass CR spec and a broken link
Update to talos v0.11 docs
> fix: broken url, ServerClass CR spec

- app/sidero-controller-manager/config/manager/manager.yaml
- app/sidero-controller-manager/internal/healthz/healthz.go
- app/sidero-controller-manager/main.go
Fixes #560
The way it was implemented before this change, `errgoup` waits for all
goroutines to finish before it returns, so if the controller crashes due
to election issues, container still keeps running as HTTP API is up.
After this change, container crashes on first error.
Also added liveness/readiness check, they won't help much this issue,
but provide additional layer of protection/visibility.
> fix: shutdown sidero-controller-manager when any component fails

- app/sidero-controller-manager/config/manager/manager.yaml
- app/sidero-controller-manager/internal/healthz/healthz.go
- app/sidero-controller-manager/main.go
Fixes #560
The way it was implemented before this change, `errgoup` waits for all
goroutines to finish before it returns, so if the controller crashes due
to election issues, container still keeps running as HTTP API is up.
After this change, container crashes on first error.
Also added liveness/readiness check, they won't help much this issue,
but provide additional layer of protection/visibility.
(cherry picked from commit e52071d7f9e5a05dc8b3f9d2ee48265a55c6fc14)
> backport: fix: shutdown sidero-controller-manager when any component fails

- .drone.yml
We need 20+ to get cgroupsv2 compatibility.
> chore: fix docker version in the drone pipeline

- website/content/docs/v0.4/Guides/sidero-on-rpi4.md
talosctl generates YAML files with the .yaml extension, update to the apply-config command to reflect this
Signed-off-by: Charlie Haley <charlie.haley@hotmail.com>
> fix: update extension for controlplane.yaml 

- app/sidero-controller-manager/main.go
Fixes #502
The value is simply parsed as Linux kernel command line arguments.
> docs: update help message for extra kernel args

- app/sidero-controller-manager/cmd/agent/main.go
- app/sidero-controller-manager/controllers/server_controller.go
- app/sidero-controller-manager/internal/power/api/api.go
- app/sidero-controller-manager/internal/power/ipmi/ipmi.go
- app/sidero-controller-manager/internal/power/metal/fake.go
- app/sidero-controller-manager/internal/power/metal/metal.go
- go.mod
- go.sum
Fixes #468
This removes IPMI password from command line arguments.
Sidero was fixed to use `Open`/`Close` with goipmi client.
See:
* https://github.com/talos-systems/goipmi/pull/2
* https://github.com/talos-systems/goipmi/pull/3
> fix: hide password from ipmitool args

- app/sidero-controller-manager/api/v1alpha1/environment_types.go
- app/sidero-controller-manager/internal/ipxe/ipxe_server.go
- sfyra/pkg/tests/environment.go
- website/content/docs/v0.5/Guides/first-cluster.md
- website/content/docs/v0.5/Resource Configuration/environments.md
Fixes #460
With this change, it's no longer necessary to supply `talos.config` in
the Environment - it is appended dynamically during the boot process.
So `talos.config` is removed even from the default Environment, as this
makes it update automatically if Sidero endpoint gets changed.
> feat: automatically append talos.config to the Environment

- sfyra/README.md
As Sidero is now on 0.4.0, we need to build with proper tag to make CAPI
pick up proper API cotnract.
> test: fix Sidero components version in sfyra docs

- templates/cluster-template.yaml
It worked before as it was being migrated from `v1alpha3` to `v1alpha4` when applied.
Fixes: https://github.com/talos-systems/sidero/issues/628
> fix: update CAPI resources versions to v1alpha4 in the cluster template

- Dockerfile
- app/sidero-controller-manager/cmd/events-manager/adapter.go
- app/sidero-controller-manager/cmd/events-manager/kubernetes.go
- app/sidero-controller-manager/cmd/events-manager/main.go
- app/sidero-controller-manager/config/manager/manager.yaml
- app/sidero-controller-manager/internal/ipxe/ipxe_server.go
- app/sidero-controller-manager/internal/siderolink/siderolink.go
- set up `talos.events.sink` kernel args.
- build and run additional container to receive talos events.
- log all events in the adapter.
> feat: implement events manager container

- app/sidero-controller-manager/controllers/server_controller.go
- app/sidero-controller-manager/pkg/constants/constants.go
Sometimes if power off event is followed by server allocation
immediately, IPMI might "lie" about power status of the server.
Server is being powered off, while it reports power on status.
In this case Sidero might fail to power on an allocated Server.
Workaround that by checking for power state in this state.
> fix: check for server power state when in use

- sfyra/cmd/sfyra/cmd/options.go
This is release-0.3 only fix to make tests work properly.
> test: fix compatibility by locking down v1alpha3 provider versions

- app/sidero-controller-manager/internal/ipxe/ipxe_server.go
- app/sidero-controller-manager/internal/ipxe/ipxe_test.go
With this change, iPXE now prints information about available network
interfaces and configured IP after DHCP.
It should also retry DHCP but it's hard to test in my environment.
Also different interface should be tried if loading `/ipxe` script
fails.
Example:
```
net0: 4e:65:61:9e:84:a4 using undionly on 0000:00:02.0 (closed)
[Link:up, TX:0 TXE:1 RX:0 RXE:0]
[TXE: 1 x "Network unreachable (http://ipxe.org/28086011)"]
Configuring (net0 4e:65:61:9e:84:a4)...... ok
net0: 172.25.0.3/255.255.255.0 gw 172.25.0.1
http://172.24.0.2:8081/ipxe... ok
/env/agent-amd64/vmlinuz... ok
```
> feat: extend information printed in the iPXE script, add retries

- app/sidero-controller-manager/cmd/agent/main.go
This PR changes the order of operations so that the BMC gets setup after
the disk wipes occur. This lets us avoid an issue where we could
accidentally power off the box during wiping.
> fix: ensure we setup BMC info *after* disk wiping

- Makefile
- app/caps-controller-manager/api/v1alpha3/metalmachine_conditions.go
- app/sidero-controller-manager/cmd/events-manager/adapter.go
- app/sidero-controller-manager/controllers/server_controller.go
- app/sidero-controller-manager/internal/ipxe/ipxe_server.go
- hack/release.toml
- hack/scripts/integration-test.sh
- sfyra/cmd/sfyra/cmd/options.go
- sfyra/cmd/sfyra/cmd/test_integration.go
- sfyra/pkg/tests/cluster_utils.go
- sfyra/pkg/tests/compatibility.go
- sfyra/pkg/tests/server.go
- sfyra/pkg/tests/tests.go
- sfyra/pkg/tests/workload_cluster.go
- templates/cluster-template-talos-v0.13.4.yaml
Now `PXEBooted` condition is derived from `TalosInstalled` condition of
the linked `ServerBinding`.
This makes the node to use `pxe` boot until Talos installation succeeds.
> feat: set server PXEBooted condition only after Talos gets installed

- Makefile
Next release of Sidero will probably cover lifetime of the next Talos
version, so better to keep kernels closer in the agent and Talos Linux.
> chore: bump pkgs to include latest kernel into the agent environment

- app/caps-controller-manager/controllers/metalmachine_controller.go
- app/caps-controller-manager/controllers/serverbinding_controller.go
- app/sidero-controller-manager/cmd/agent/main.go
- app/sidero-controller-manager/controllers/environment_controller.go
- app/sidero-controller-manager/controllers/server_controller.go
- app/sidero-controller-manager/controllers/serverclass_controller.go
- app/sidero-controller-manager/controllers/suite_test.go
- app/sidero-controller-manager/internal/ipxe/ipxe_server.go
- app/sidero-controller-manager/internal/metadata/metadata_server.go
- app/sidero-controller-manager/internal/power/api/api.go
- app/sidero-controller-manager/internal/power/factory.go
- app/sidero-controller-manager/internal/power/ipmi/ipmi.go
- app/sidero-controller-manager/internal/server/server.go
- app/sidero-controller-manager/main.go
- internal/client/client.go
- sfyra/pkg/capi/cluster.go
- sfyra/pkg/capi/metalclient.go
- sfyra/pkg/loadbalancer/loadbalancer.go
- sfyra/pkg/tests/compatibility.go
- sfyra/pkg/tests/environment.go
- sfyra/pkg/tests/match.go
- sfyra/pkg/tests/reconcile.go
- sfyra/pkg/tests/reset.go
- sfyra/pkg/tests/server.go
- sfyra/pkg/tests/server_class.go
Imports should be consistently named so future changes are more readable and easier to understand.
Signed-off-by: Gerard de Leeuw <gdeleeuw@leeuwit.nl>
> chore: use consistent naming for imports

- website/content/v0.2/Getting Started/prereq-dhcp.md
- website/content/v0.3/Getting Started/prereq-dhcp.md
- website/content/v0.4/Getting Started/prereq-dhcp.md
- website/content/v0.5/Getting Started/prereq-dhcp.md
This PR fixes a turbo-nit where the configs for the DHCP settings
weren't getting processed as code blocks
> docs: switch code block to text for DHCP prereq

- app/caps-controller-manager/config/default/webhookcainjection_patch.yaml
- app/caps-controller-manager/main.go
- app/sidero-controller-manager/api/v1alpha1/environment_webhook.go
- app/sidero-controller-manager/api/v1alpha1/server_webhook.go
- app/sidero-controller-manager/api/v1alpha1/serverclass_webhook.go
- app/sidero-controller-manager/api/v1alpha1/zz_generated.deepcopy.go
- app/sidero-controller-manager/config/certmanager/certificate.yaml
- app/sidero-controller-manager/config/crd/kustomization.yaml
- app/sidero-controller-manager/config/crd/kustomizeconfig.yaml
- app/sidero-controller-manager/config/crd/patches/cainjection_in_environments.yaml
- app/sidero-controller-manager/config/crd/patches/cainjection_in_serverclasses.yaml
- app/sidero-controller-manager/config/crd/patches/cainjection_in_servers.yaml
- app/sidero-controller-manager/config/crd/patches/webhook_in_environments.yaml
- app/sidero-controller-manager/config/crd/patches/webhook_in_serverclasses.yaml
- app/sidero-controller-manager/config/crd/patches/webhook_in_servers.yaml
- app/sidero-controller-manager/config/kustomization.yaml
- app/sidero-controller-manager/config/manager_webhook_patch.yaml
- app/sidero-controller-manager/config/webhook/kustomization.yaml
- app/sidero-controller-manager/config/webhook/manifests.yaml
- app/sidero-controller-manager/config/webhook/service.yaml
- app/sidero-controller-manager/config/webhookcainjection_patch.yaml
- app/sidero-controller-manager/main.go
- sfyra/pkg/tests/server.go
- sfyra/pkg/tests/tests.go
Based on https://github.com/siderolabs/sidero/pull/794, but instead of
using a dedicated controller for all webhooks keep all of them in each
own controller.
Additionally, implement validation webhooks for `Server` resource, which
validates that `bootFromDiskMethod` and `configPatches` are using proper
values.
> feat: enable webhooks in `sidero-controller-manager`

- Makefile
- app/caps-controller-manager/controllers/metalmachine_controller.go
- app/caps-controller-manager/controllers/serverbinding_controller.go
- app/caps-controller-manager/main.go
- app/sidero-controller-manager/api/v1alpha1/environment_types.go
- app/sidero-controller-manager/controllers/server_controller.go
- go.mod
- sfyra/cmd/sfyra/cmd/options.go
- sfyra/pkg/tests/reconcile.go
- sfyra/pkg/tests/tests.go
- website/.gitignore
This PR has two major changes:
* retire the code which supported seamless migration from
pre-ServerBinding era to ServerBindings: creating `ServerBinding` on the
fly from the `MetalMachine` and `Server`; as there's no migration path
from pre-ServerBinding Sidero to the new version, it's time to drop it
* instead of creating workload cluster Kubernetes client each time, use
CAPI standard class to cache the client; the problem with "leaking"
clients is that HTTP/2 clients are almost never gc'ed, so they stay in
memory keeping an open connection with keepalives going both ways, so
caching lowers the load both on the controller and the control plane
endpoint
> refactor: remove pre-ServerBinding leftovers, use remote cached clients

- app/caps-controller-manager/api/v1alpha3/metalmachinetemplate_webhook.go
- app/caps-controller-manager/api/v1alpha3/zz_generated.deepcopy.go
- app/caps-controller-manager/config/default/kustomization.yaml
- app/caps-controller-manager/config/webhook/kustomization.yaml
- app/caps-controller-manager/config/webhook/manifests.yaml
- go.mod
This allows proper upgrades by replacing the `MetalMachineTemplate`.
If the `MetalMachineTemployment` is mutated, the changes are not rolled
out automatically.
> feat: make MetalMachineTemplate immutable

- app/sidero-controller-manager/internal/ipxe/ipxe_server.go
If the server or environment used by the machine had at least one kernel
param overriden, the `ipxe_server` was skipping adding all of them.
Instead of that skip only the parameters which were defined.
> fix: append Talos default kernel args even if there is some defined

- website/content/v0.5/Guides/rpi4-as-servers.md
- website/content/v0.6/Guides/rpi4-as-servers.md
Updated "Raspberry Pi 4's as Servers" guide with learnings from [this](https://taloscommunity.slack.com/archives/CMARMBC4E/p1654714688959959) Slack thread.
> docs: use ipxe-sanboot for raspberry pi 4's

- app/sidero-controller-manager/internal/ipxe/ipxe_server.go
Fixes an issue with fmt.Fprint formatting byte arrays.
Fixes https://github.com/siderolabs/sidero/issues/889
I'm currently running with this change via `ghcr.io/bzub/sidero-controller-manager:v0.5.1-1-g7fe8dcb`.
Signed-off-by: bzub <bzub@users.noreply.github.com>
> fix: use http response writer directly

- Dockerfile
- app/sidero-controller-manager/cmd/agent/main.go
- go.mod
- go.sum
- sfyra/go.mod
- sfyra/go.sum
This brings new blockdevice library with read-only bd detection.
> fix: skip read-only block devices on wiping

- app/sidero-controller-manager/cmd/events-manager/adapter.go
This address is only useful within the context of the Sidero pod, and
e.g. control plane provider can't talk over it, so excluding the address
helps to avoid additional failures in the CP provider.
> fix: filter out SideroLink address from Machine addresses

- netlify.toml
- website/assets/scss/_styles_project.scss
- website/layouts/partials/doc_latest_version.html
- website/layouts/partials/hooks/head-end.html
- website/layouts/partials/version-banner.html
This PR is a copy of two PRs from talos:
https://github.com/siderolabs/talos/pull/5389/files
https://github.com/siderolabs/talos/pull/5391/files
It ensures that the banner is shown if the user isn't viewing the latest sidero docs. This actually already was working but the banner html was in an incorrect spot, so moved that to match what's seen in Talos repo. Also adds the canonical links for search engines to update their indexes.
> docs: handle latest version banner and canonical urls

- .drone.yml
- app/sidero-controller-manager/cmd/agent/main.go
- sfyra/pkg/constants/constants.go
This is classic Go bug with using variable of a for loop in a closure :(
This leads to random disks being skipped/not-skipped as readonly on disk
wiping.
> fix: properly inspect readonly flag of the disk

- .drone.yml
- app/sidero-controller-manager/cmd/agent/main.go
- sfyra/pkg/constants/constants.go
fix: properly inspect readonly flag of the disk
This is classic Go bug with using variable of a for loop in a closure :(
This leads to random disks being skipped/not-skipped as readonly on disk
wiping.
(cherry picked from commit 44f1962ceaac518f1e59205a43db3a1bf1e79cd6)
> backports: for v0.5.4

- netlify.toml
- website/layouts/partials/hooks/head-end.html
Fixes canonical link for the documentation website.
Signed-off-by: Tim Jones <tim.jones@siderolabs.com>
> fix: canonical links in docs site

- website/content/v0.6/Resource Configuration/serverclasses.md
Link from Server Classes guide to patching guide fixed.
Signed-off-by: Tim Jones <tim.jones@siderolabs.com>
> docs: fix dead link in serverclasses guide

- website/layouts/sitemap.xml
Fixes the missing "www." prefix to the url in the
sitemap section of the docs website.
Signed-off-by: Tim Jones <tim.jones@siderolabs.com>
> fix: docs sitemap www prefix

- app/sidero-controller-manager/api/v1alpha1/server_types.go
- app/sidero-controller-manager/api/v1alpha1/server_webhook.go
- app/sidero-controller-manager/api/v1alpha1/zz_generated.conversion.go
- app/sidero-controller-manager/api/v1alpha2/server_types.go
- app/sidero-controller-manager/api/v1alpha2/server_webhook.go
- app/sidero-controller-manager/config/crd/bases/metal.sidero.dev_servers.yaml
- app/sidero-controller-manager/controllers/server_controller.go
- app/sidero-controller-manager/internal/power/api/api.go
- app/sidero-controller-manager/internal/power/fake.go
- app/sidero-controller-manager/internal/power/ipmi/ipmi.go
- app/sidero-controller-manager/internal/power/metal/metal.go
- app/sidero-controller-manager/main.go
- app/sidero-controller-manager/pkg/types/types.go
This adds a new field to the `Server` resource which can be used to override default IPMI PXE boot method.
Fixes #987
> feat: provide a way to override IPMI PXE boot method on `Server`

- app/sidero-controller-manager/api/v1alpha1/server_types.go
- app/sidero-controller-manager/config/crd/bases/metal.sidero.dev_servers.yaml
- app/sidero-controller-manager/controllers/server_controller.go
- app/sidero-controller-manager/internal/power/api/api.go
- app/sidero-controller-manager/internal/power/fake.go
- app/sidero-controller-manager/internal/power/ipmi/ipmi.go
- app/sidero-controller-manager/internal/power/metal/metal.go
- app/sidero-controller-manager/main.go
- app/sidero-controller-manager/pkg/types/types.go
This adds a new field to the `Server` resource which can be used to override default IPMI PXE boot method.
Fixes #987
(cherry picked from commit d8ef68b6b951df093d288c1dae6c0d32a9e00aec)
> backport: feat: provide a way to override IPMI PXE boot method on `Server`

- website/content/v0.1/Guides/bootstrapping.md
- website/content/v0.2/Getting Started/prereq-dhcp.md
- website/content/v0.2/Guides/bootstrapping.md
- website/content/v0.3/Getting Started/prereq-dhcp.md
- website/content/v0.3/Guides/bootstrapping.md
- website/content/v0.4/Getting Started/prereq-dhcp.md
- website/content/v0.4/Guides/bootstrapping.md
- website/content/v0.5/Getting Started/prereq-dhcp.md
- website/content/v0.5/Guides/bootstrapping.md
- website/content/v0.6/Getting Started/prereq-dhcp.md
- website/content/v0.6/Guides/bootstrapping.md
The docs currently suggest placing the ipxe configuration file in /etc/dhcp/ - while this seems sane, when you update the firmware of an EdgeOS Device, which this is geared towards (or any other vyatta-based device), the entire filesystem is wiped, other than the /config directory.
This becomes especially problematic, because the config itself will still reference this file, and the dhcp server will refuse to start. From /var/log/messsages:
```
Oct 29 00:17:03 ubnt systemd[1]: vyatta-dhcpd.service: Control process exited, code=exited status=1
Oct 29 00:17:03 ubnt systemd[1]: Failed to start EdgeOS DHCP Server.
Oct 29 00:17:03 ubnt systemd[1]: vyatta-dhcpd.service: Unit entered failed state.
Oct 29 00:17:03 ubnt systemd[1]: vyatta-dhcpd.service: Failed with result 'exit-code'.
Oct 29 …
```
> fix: docs: /etc/dhcp -> config to preserve across firmware update

- app/sidero-controller-manager/internal/ipxe/patch.go
- website/content/v0.6/Getting Started/expose-services.md
- website/content/v0.6/Getting Started/prereq-dhcp.md
- website/content/v0.6/Getting Started/troubleshooting.md
- website/content/v0.6/Guides/bootstrapping.md
- website/content/v0.6/Guides/first-cluster.md
> feat: provide 'snp.efi' and recommend it over 'ipxe.efi'

- app/sidero-controller-manager/controllers/server_controller.go
- app/sidero-controller-manager/internal/ipxe/ipxe_server.go
- app/sidero-controller-manager/internal/metadata/fixture_test.go
- app/sidero-controller-manager/internal/metadata/metadata_server.go
- app/sidero-controller-manager/internal/metadata/metadata_server_test.go
- go.mod
- sfyra/pkg/bootstrap/cluster.go
- sfyra/pkg/loadbalancer/loadbalancer.go
- sfyra/pkg/tests/server.go
Previous PR used Talos machinery to load the config, and then generate config patch to patch the config. This worked fine until Talos started validating loaded machine config for 'unknown fields'. This breaks this flow, as Omni Talos machinery version should be >= Talos version.
Rewriting the code to skip loading using Talos machinery, also handle cases of broken config without `machine` or `machine.kubelet` sections. These will probably be invalid anyways, but we let Talos report it instead of panic in Sidero.
Fixes #1076
Also use Talos machinery configpatcher to reduce code duplication.
And, last but not the least, add a unit-test for the metadata server, which covers all major code paths.
```
ok  	github.com/siderolabs/sidero/app/sidero-controller-manager/internal/metadata	0.022s …
```
> fix: break the link of metadata server to Talos machine config

- app/sidero-controller-manager/cmd/agent/bmc.go
- app/sidero-controller-manager/cmd/agent/main.go
> fix: allow 'empty user' slots to be used in IPMI setup

- app/sidero-controller-manager/cmd/siderolink-manager/main.go
This was breaking for IPv6 addresses.
Closes #1116
(This is a better/shorter fix).
> fix: build siderolink endpoint correctly

- website/content/v0.4/Getting Started/prereq-cli-tools.md
- website/content/v0.5/Getting Started/prereq-cli-tools.md
- website/content/v0.6/Getting Started/prereq-cli-tools.md
`sudo` begins a new command, so the preceding line must not end in `\`.
> docs: remove excess bash continuation backslashes

- website/static/_redirects
The website currently redirects to 0.5 instead of 0.6
> docs: fix website redirect to latest version

- website/content/v0.6/Guides/bootstrapping.md
I've updated the docs to reflect the use of "controlplane" vs. "master" in the bootstrapping guide. I also updated the examples to use the last stable versions of Kubernetes (1.29.0) and Talos (1.6.1).
> docs: Update bootstrap guide to reflect controlplane host name and stable versions

- app/caps-controller-manager/main.go
- app/sidero-controller-manager/main.go
See https://github.com/siderolabs/cluster-api-bootstrap-provider-talos/issues/185
> fix: set a default controller runtime log

- app/sidero-controller-manager/internal/dhcp/dhcp_server.go
We need to use EFI version of iPXE.
Fixes #1295
> fix: update HTTP boot filename

- README.md
- website/content/_index.html
- website/content/v0.6/_index.md
Refer to the bare metal infra provider, as it is the spiritual successor of Sidero Metal.
> docs: add Omni bare metal infra provider link to maintenance warning
