siderolabs/sidero

.drone.yml
This enables us to run in the new kube pipeline types.
=> chore: update drone pipeline type

.conform.yaml, .markdownlint.json, CHANGELOG.md, Dockerfile, hack/chglog/CHANGELOG.tpl.md, hack/chglog/config.yml, hack/release.sh
This is the official v0.1.0-alpha.0 release.
=> release(v0.1.0-alpha.0): prepare release

.drone.yml
This PR will inject the drone tag so github_release knows where to look
for release files.
=> chore: update drone file for tagged releases

internal/app/cluster-api-provider-sidero/controllers/metalmachine_controller.go
This PR fixes a bug encountered when pivoting clusters where we weren't
updating in-use status on every reconcile loop. Statuses aren't copied
over with a `clusterctl move`, so we need to make sure it gets updated.
=> fix: ensure servers always get patched

docs/website/content/docs/concepts.md, docs/website/content/docs/environments.md, docs/website/content/docs/installation.md, docs/website/content/docs/patching.md, docs/website/content/docs/serverclasses.md, docs/website/content/docs/servers.md
This PR adds a bunch of extra info and explanation around our various docs. I will likely be chasing this PR with a big update to the bootstrapping guide to cover pivoting and all that.
=> docs: iterate on docs

CHANGELOG.md, hack/release.sh
This is the official v0.1.0-alpha.1 release.
=> release(v0.1.0-alpha.1): prepare release

app/cluster-api-provider-sidero/controllers/metalmachine_controller.go
This PR adds ownership to servers based on the serverclass they were
selected from. This will allow us to target environments at the
serverclass level and apply it to a given server.
=> feat: add serverclass as an owner to servers if needed

app/cluster-api-provider-sidero/config/default/kustomization.yaml, app/metal-controller-manager/config/kustomization.yaml, app/metal-metadata-server/config/kustomization.yaml, config/namespace.yaml, docs/website/content/docs/bootstrapping.md
This PR updates the namespace to align with other Cluster API providers.
Will close #33
=> chore: update namespace to caps-system

app/cluster-api-provider-sidero/controllers/metalmachine_controller.go
This PR fixes a bug where servers were still getting allocated to
multiple metalmachines b/c we were using a Patch instead of an Update to
set the "inUse" status. This resulted in no error being thrown when
multiple metalmachines tried to claim the same server.
=> fix: move to update instead of patching server inuse

app/cluster-api-provider-sidero/config/manager/manager.yaml, app/cluster-api-provider-sidero/config/prometheus/monitor.yaml, app/cluster-api-provider-sidero/config/rbac/auth_proxy_service.yaml, app/cluster-api-provider-sidero/config/webhook/service.yaml, app/metal-controller-manager/config/manager/manager.yaml, app/metal-controller-manager/config/prometheus/monitor.yaml, app/metal-controller-manager/config/rbac/auth_proxy_service.yaml, app/metal-controller-manager/config/webhook/service.yaml, app/metal-metadata-server/config/server/server.yaml
This PR updates the labels that get set for each of the sidero apps to
ensure that label selection has no conflicts for services.
=> fix: update labels and labelselectors for each app

sfyra/README.md
Some changes related to merge with Sidero project.
=> docs: update Sfyra docs

.drone.yml, hack/scripts/integration-test.sh
Use new 'secure' registry  reference.
=> chore: update reference to internal registry

.drone.yml, sfyra/pkg/tests/reset.go, sfyra/pkg/tests/tests.go
Adds a test for server resets.
=> test: add reset test

.conform.yaml, CHANGELOG.md
This is the official v0.1.0-alpha.2 release.
=> release(v0.1.0-alpha.2): prepare release

sfyra/pkg/capi/cluster.go
This fixes the Talos health check by providing the expected set of nodes
from the CAPI point of view. This makes sure Talos cluster state matches
CAPI state.
=> test: provide list of expected control plane/worker nodes

sfyra/pkg/capi/capi.go
Patch has never been applied actually.
=> test: fix patching for sidero-controller-manager

app/cluster-api-provider-sidero/controllers/metalmachine_controller.go
The problem here was that there were two `Update()`s, one for `Status`
and another one for the `Spec` essentially. `Status` update could have
succeeded and marked server as `InUse`, while `Spec` update failed on
conflict error.
As we ignore conflict errors one level up, server was marked as `InUse`
while never attached to any `MetalMachine`, so it was left as orphaned.
=> fix: handle conflicts on server update

Makefile, app/metal-controller-manager/controllers/environment_controller.go, app/metal-controller-manager/internal/ipxe/ipxe_server.go, app/metal-controller-manager/pkg/constants/constants.go, hack/scripts/integration-test.sh, sfyra/cmd/sfyra/cmd/bootstrap_capi.go, sfyra/cmd/sfyra/cmd/bootstrap_cluster.go, sfyra/cmd/sfyra/cmd/bootstrap_servers.go, sfyra/cmd/sfyra/cmd/loadbalancer_create.go, sfyra/cmd/sfyra/cmd/options.go, sfyra/cmd/sfyra/cmd/test_integration.go, sfyra/go.mod, sfyra/go.sum, sfyra/pkg/bootstrap/cluster.go
In 0.7.0-alpha.4, asset names got changed slightly.
=> chore: update Sfyra for the new Talos release

app/metal-controller-manager/controllers/environment_controller.go
This should make method shorter and (hopefully) more readable.
Tried to elliminate duplicated blocks.
=> chore: refactor `reconcile` method in `environment_controller.go`

Dockerfile, app/cluster-api-provider-sidero/controllers/metalmachine_controller.go, app/metal-controller-manager/internal/ipxe/ipxe_server.go, sfyra/cmd/sfyra/cmd/options.go, sfyra/pkg/capi/cluster.go, sfyra/pkg/loadbalancer/loadbalancer.go, sfyra/pkg/tests/management_cluster.go, sfyra/pkg/tests/reset.go, sfyra/pkg/tests/scale.go, sfyra/pkg/tests/tests.go
Adds a test for scaling workers and control plane.
=> test: add scale test

app/metal-controller-manager/cmd/agent/main.go
Instead of exiting (which causes a kernel panic), we shutdown instead.
=> fix: handle agent errors gracefully

CHANGELOG.md
This is the official v0.1.0-alpha.4 release.
=> release(v0.1.0-alpha.4): prepare release

CHANGELOG.md
This is the official v0.1.0-alpha.5 release.
=> release(v0.1.0-alpha.5): prepare release

CHANGELOG.md
This is the official v0.1.0-alpha.6 release.
=> release(v0.1.0-alpha.6): prepare release

app/metal-controller-manager/cmd/agent/main.go, go.mod, go.sum
As wiping a disk might take considerable time, it makes sense to wipe
them all concurrently.
=> feat: wipe disks concurrently in the agent

app/cluster-api-provider-sidero/controllers/metalmachine_controller.go
Log actual error with error log.
=> fix: log error with error log

docs/website/gridsome.config.js, docs/website/static/robots.txt
Fixes a few minor issues with the docs website.
=> docs: update site URL and add robots.txt

docs/website/content/docs/v0.1/Guides/bootstrapping.md, docs/website/content/docs/v0.1/Guides/first-cluster.md
This PR adds server acceptance to the bootstrap guide.
Will close #177 
=> docs: add note around server acceptance

docs/website/content/docs/v0.1/Guides/bootstrapping.md, docs/website/content/docs/v0.1/Guides/first-cluster.md
This PR fixes a docs bug where I introduced incorrect links.
=> docs: update bootstrap docs links

docs/website/content/docs/v0.1/Guides/bootstrapping.md, docs/website/content/docs/v0.1/Guides/first-cluster.md
This PR addresses the fact that I can't type :facepalm:.
=> docs: fix typos in bootstrap guides

Dockerfile
=> fix: update pkgs

app/cluster-api-provider-sidero/controllers/metalmachine_controller.go
This is an acceptable condition and should not be treated as an error.
=> refactor: add ErrNoServersInServerClass

app/metal-controller-manager/cmd/agent/main.go, go.mod, go.sum, sfyra/go.sum
Share the same code with Talos `Disks` grpc.
=> refactor: use GetDisks from blockdevice library

CHANGELOG.md
This is the official v0.1.0-alpha.10 release.
=> release(v0.1.0-alpha.10): prepare release

app/cluster-api-provider-sidero/controllers/metalmachine_controller.go, app/metal-controller-manager/controllers/server_controller.go
Instead of powering on a server in MetalMachineController, unify the
power management under ServerController.
Also mark server as dirty when it's not accepted to make sure server is
wiped if it goes through !accepted -> accepted transition.
=> refactor: unify power management under ServerController

app/cluster-api-provider-sidero/config/manager/manager.yaml, app/metal-controller-manager/config/manager/manager.yaml, app/metal-metadata-server/config/server/server.yaml, sfyra/cmd/sfyra/cmd/options.go
=> fix: bump resource limits for the sidero pods

docs/website/content/docs/v0.1/Guides/patching.md
=> docs: fix patching example

CHANGELOG.md
This is the official v0.1.0-alpha.11 release.
=> release(v0.1.0-alpha.11): prepare release

docs/website/package-lock.json, docs/website/package.json
Hoping that this fixes analytics.
=> chore: bump google analytics plugin

docs/website/gridsome.config.js, docs/website/package-lock.json, docs/website/package.json
We need to use a plugin for the Google Tag Manager service.
=> chore: fix analytics

docs/website/content/docs/v0.1/Guides/flow.md, docs/website/gridsome.config.js, docs/website/package-lock.json, docs/website/package.json
Adds flow charts describing the PXE boot and installation processes.
=> docs: add flow charts for PXE and installation

docs/website/content/docs/v0.1/Configuration/environments.md, docs/website/content/docs/v0.1/Configuration/metadata.md, docs/website/content/docs/v0.1/Configuration/serverclasses.md, docs/website/content/docs/v0.1/Guides/patching.md
=> docs: improve docs on metadata and environments

sfyra/README.md
Document `TAG`, running tests once more, etc.
=> docs: update local Sfyra docs

CHANGELOG.md
This is the official v0.1.0-beta.0 release.
=> release(v0.1.0-beta.0): prepare release

docs/website/content/docs/v0.1/Configuration/environments.md, docs/website/content/docs/v0.1/Configuration/servers.md, docs/website/content/docs/v0.1/Getting Started/resources.md, sfyra/pkg/capi/cluster.go, sfyra/pkg/tests/reconcile.go
Update environment kernel args and links to the latest Talos release,
add IPMI info, fix random broken links.
=> docs: add IPMI info, fix links, update environment

sfyra/pkg/capi/cluster.go
Skip Machines marked for deletion.
(cherry picked from commit 01706b2228cce61e29827b3b9c6f27a0f0c0b3b3)
=> test: fix test flakiness on workers scale down test

docs/website/gridsome.config.js, docs/website/package-lock.json, docs/website/package.json
Uses the legacy Google Analytics service.
=> docs: setup google analytics

.conform.yaml, CHANGELOG.md
This is the official v0.2.0-alpha.0 release.
=> release(v0.2.0-alpha.0): prepare release

CHANGELOG.md, config/metadata/metadata.yaml, hack/release.sh
This is the official v0.2.0-alpha.1 release.
=> release(v0.2.0-alpha.1): prepare release

app/metal-metadata-server/main.go
This fixes the issue with config fields in the machine configuration
introduced in new versions of Talos being lost when configuration is
delivered via the Sidero metadata server.
Instead of marshaling config using machinery, build a config patch to be
applied to fix up kubelet extra args.
P.S. extraArgs structure is really hard to use with configPatches today
as it can be seen from this PR, there's no way to build "easy" patch, as
patch depends on existing extraArgs value.
Fixes #295
=> fix: don't marshal the machine configuration via machinery package

CHANGELOG.md
This is the official v0.2.0-beta.0 release.
=> release(v0.2.0-beta.0): prepare release

docs/website/content/docs/v0.2/Guides/bootstrapping.md, docs/website/content/docs/v0.2/Guides/first-cluster.md, docs/website/content/docs/v0.3/Guides/bootstrapping.md, docs/website/content/docs/v0.3/Guides/first-cluster.md
We actually have two variables, not one variable.
=> docs: fix the docs around CONTROL_PLANE_ENDPOINT

.github/dependabot.yml
=> chore: disable dependabot rebases

Makefile
=> chore: document Makefile target

.drone.yml, app/cluster-api-provider-sidero/controllers/suite_test.go, app/metal-controller-manager/controllers/suite_test.go
=> test: run unit tests on CI, skip broken

app/cluster-api-provider-sidero/api/v1alpha2/v1alpha2_test.go, app/cluster-api-provider-sidero/api/v1alpha3/v1alpha3_test.go, app/metal-controller-manager/api/v1alpha1/v1alpha1_test.go, app/metal-controller-manager/internal/ipxe/ipxe_test.go, app/metal-controller-manager/internal/power/api/api_test.go, app/metal-controller-manager/internal/power/ipmi/ipmi_test.go, app/metal-controller-manager/internal/power/metal/metal_test.go, app/metal-controller-manager/internal/server/server_test.go, app/metal-controller-manager/internal/tftp/tftp_test.go, app/metal-metadata-server/pkg/client/client_test.go
For accurate coverage estimation.
=> test: add missing empty tests

docs/website/content/docs/v0.1/Configuration/servers.md, docs/website/content/docs/v0.2/Configuration/servers.md, docs/website/content/docs/v0.3/Configuration/servers.md
We should not boo the network.
=> docs: fix typo

Dockerfile, Makefile, app/cluster-api-provider-sidero/main.go, app/metal-controller-manager/cmd/agent/main.go, app/metal-controller-manager/config/crd/bases/metal.sidero.dev_servers.yaml, app/metal-controller-manager/main.go, app/metal-metadata-server/main.go, go.mod, go.sum, internal/client/client.go, sfyra/cmd/sfyra/cmd/root.go, sfyra/go.mod, sfyra/go.sum
Refs talos-systems/talos#3534.
=> chore: allow building with debug handlers

Makefile, go.mod, go.sum, hack/parsebool.sh, sfyra/go.mod, sfyra/go.sum
Makes `make WITH_DEBUG=1` work.
Closes talos-systems/talos#3534.
=> chore: parse "boolean" variables

.conform.yaml, CHANGELOG.md, config/metadata/metadata.yaml, hack/chglog/config.yml
This is the official v0.3.0-alpha.0 release.
=> release(v0.3.0-alpha.0): prepare release

.drone.yml
=> chore: re-sign the .drone.yml file

Dockerfile, go.mod, go.sum, sfyra/go.mod, sfyra/go.sum
=> chore: bump dependencies via dependabot

.golangci.yml, app/cluster-api-provider-sidero/api/v1alpha2/groupversion_info.go, app/cluster-api-provider-sidero/api/v1alpha3/groupversion_info.go, app/cluster-api-provider-sidero/controllers/suite_test.go, app/metal-controller-manager/api/v1alpha1/groupversion_info.go, app/metal-controller-manager/controllers/suite_test.go, app/metal-controller-manager/internal/metadata/metadata_server.go
=> chore: fix a few linter warnings

Dockerfile, app/metal-controller-manager/api/v1alpha1/environment_types.go, app/metal-controller-manager/config/samples/metal_v1alpha1_environment.yaml, app/metal-controller-manager/controllers/environment_controller.go, app/metal-controller-manager/internal/ipxe/ipxe_server.go, app/metal-controller-manager/main.go, docs/website/content/docs/v0.3/Configuration/environments.md, docs/website/content/docs/v0.3/Guides/bootstrapping.md, docs/website/content/docs/v0.3/Guides/first-cluster.md, docs/website/content/docs/v0.3/Guides/upgrades.md, go.mod, go.sum, sfyra/cmd/sfyra/cmd/options.go, sfyra/go.mod, sfyra/go.sum, sfyra/pkg/tests/environment.go, sfyra/pkg/tests/server_class.go, sfyra/pkg/tests/tests.go
=> feat: ship Environment "default"

website/gridsome.config.js, website/package-lock.json, website/package.json
Adds the missing Mermaid plugin to render flowcharts.
=> docs: add Mermaid

CHANGELOG.md, hack/release.toml
This is the official v0.3.0-alpha.1 release.
=> release(v0.3.0-alpha.1): prepare release

Dockerfile, Makefile
Plus don't strip debug symbols in debug mode.
=> chore: add support for WITH_RACE

app/metal-controller-manager/cmd/agent/main.go, app/metal-controller-manager/internal/server/server.go
This PR makes sure that we're attempting to patch the BMC struct twice.
Once for any IP we find for the BMC info, and a second time to add the
sidero user. This ensures that we'll at least populate the IP if we can.
=> feat: always return BMC IP if found

CHANGELOG.md
This is the official v0.3.0-beta.0 release.
=> release(v0.3.0-beta.0): prepare release

website/content/docs/v0.3/Guides/rpi4-as-servers.md, website/content/docs/v0.3/Guides/sidero-on-rpi4.md
This is mostly a tutorial, as it doesn't contain any unique content, but
stitches together many guides to show easy walkthrough.
Fixes #456 
=> docs: add notes on running Sidero on RPi4

website/content/docs/v0.2/Guides/decommissioning.md, website/content/docs/v0.3/Guides/decommissioning.md
This PR adds docs that address removing a server from Sidero altogether.
=> docs: add docs for server removal/decommissioning

website/content/docs/v0.2/Guides/iso.md, website/content/docs/v0.3/Guides/iso.md, website/gridsome.config.js
As we already have Sidero 0.3 out, it's time now.
=> docs: promote 0.3 docs to be the latest

.conform.yaml, CHANGELOG.md, config/metadata/metadata.yaml, hack/release.toml
This is the official v0.4.0-alpha.0 release.
=> release(v0.4.0-alpha.0): prepare release

CHANGELOG.md
This is the official v0.4.0-alpha.1 release.
=> release(v0.4.0-alpha.1): prepare release

CHANGELOG.md, hack/release.toml
This is the official v0.3.1 release.
=> release(v0.3.1): prepare release

website/content/docs/v0.2/Getting Started/import-machines.md, website/content/docs/v0.3/Getting Started/import-machines.md, website/content/docs/v0.3/Guides/bootstrapping.md, website/content/docs/v0.3/Guides/first-cluster.md, website/content/docs/v0.3/Overview/resources.md
Fix redirects to resource configuration
=> fix: resource config links

CHANGELOG.md
This is the official v0.3.2 release.
=> release(v0.3.2): prepare release

app/sidero-controller-manager/internal/ipxe/ipxe_server.go
Fixes #558
Returning 404 error to iPXE might bring some servers into the state when
it takes a hard reboot to make it go back to network boot.
Also in line with the future changes to boot in the long-running agent
always.
=> fix: drop into the agent for non-allocated servers

Makefile
=> feat: conformance check

website/content/docs/v0.4/Getting Started/prereq-dhcp.md, website/content/docs/v0.4/Guides/bootstrapping.md
- Example of multi-arch network boot
Ref: #623
=> docs: dhcp option-93

website/content/docs/v0.3/Getting Started/prereq-dhcp.md, website/content/docs/v0.4/Getting Started/expose-services.md, website/content/docs/v0.4/Getting Started/index.md, website/content/docs/v0.4/Guides/decommissioning.md, website/content/docs/v0.4/Guides/iso.md, website/content/docs/v0.4/Overview/resources.md, website/content/docs/v0.4/Resource Configuration/metadata.md, website/content/docs/v0.5/Getting Started/expose-services.md, website/content/docs/v0.5/Getting Started/index.md, website/content/docs/v0.5/Guides/decommissioning.md, website/content/docs/v0.5/Guides/iso.md, website/content/docs/v0.5/Overview/resources.md, website/content/docs/v0.5/Resource Configuration/metadata.md
- Updates metadata server to reflect Sidero Controller Manager
- Few typos and broken links
=> docs: metadata server -> sidero

website/content/docs/v0.4/Getting Started/create-workload.md, website/content/docs/v0.4/Guides/bootstrapping.md, website/content/docs/v0.4/Guides/first-cluster.md, website/content/docs/v0.5/Getting Started/create-workload.md, website/content/docs/v0.5/Guides/bootstrapping.md, website/content/docs/v0.5/Guides/first-cluster.md
=> docs: fix clusterctl usage

CHANGELOG.md, hack/release.toml
This is the official v0.3.3 release.
=> release(v0.3.3): prepare release

website/content/docs/v0.3/Getting Started/index.md, website/content/docs/v0.4/Getting Started/index.md, website/content/docs/v0.5/Getting Started/index.md
Update Sidero requirements
Fixes #514
=> docs: reflect sidero runs on ARM

app/sidero-controller-manager/config/manager/manager.yaml, app/sidero-controller-manager/controllers/server_controller.go, app/sidero-controller-manager/internal/power/api/api.go, app/sidero-controller-manager/internal/power/factory.go, app/sidero-controller-manager/internal/power/fake.go, app/sidero-controller-manager/internal/power/ipmi/ipmi.go, app/sidero-controller-manager/internal/power/metal/metal.go, app/sidero-controller-manager/main.go, hack/release.toml, website/content/docs/v0.5/Overview/installation.md
=> feat: provide a way to configure IPMI PXE method

.conform.yaml, app/sidero-controller-manager/api/v1alpha1/environment_types.go, app/sidero-controller-manager/cmd/agent/main.go, app/sidero-controller-manager/config/manager/manager.yaml, app/sidero-controller-manager/controllers/server_controller.go, app/sidero-controller-manager/internal/ipxe/ipxe_server.go, app/sidero-controller-manager/internal/ipxe/ipxe_test.go, app/sidero-controller-manager/internal/power/api/api.go, app/sidero-controller-manager/internal/power/factory.go, app/sidero-controller-manager/internal/power/fake.go, app/sidero-controller-manager/internal/power/ipmi/ipmi.go, app/sidero-controller-manager/internal/power/metal/fake.go, app/sidero-controller-manager/internal/power/metal/metal.go, app/sidero-controller-manager/main.go, app/sidero-controller-manager/pkg/constants/constants.go, go.mod, go.sum, hack/release.toml, sfyra/pkg/tests/environment.go, templates/cluster-template.yaml
Backporting all fixes but new features like SideroLink.
=> backports: for 0.4.1 of Sidero

CHANGELOG.md, hack/release.toml
This is the official v0.4.1-beta.0 release.
=> release(v0.4.1-beta.0): prepare release

app/caps-controller-manager/api/v1alpha3/metalcluster_types.go, app/caps-controller-manager/api/v1alpha3/metalmachine_types.go, app/caps-controller-manager/api/v1alpha3/serverbinding_types.go, app/caps-controller-manager/config/crd/bases/infrastructure.cluster.x-k8s.io_metalclusters.yaml, app/caps-controller-manager/config/crd/bases/infrastructure.cluster.x-k8s.io_metalmachines.yaml, app/caps-controller-manager/config/crd/bases/infrastructure.cluster.x-k8s.io_serverbindings.yaml, app/sidero-controller-manager/api/v1alpha1/environment_types.go, app/sidero-controller-manager/api/v1alpha1/server_types.go, app/sidero-controller-manager/api/v1alpha1/serverclass_types.go, app/sidero-controller-manager/config/crd/bases/metal.sidero.dev_environments.yaml, app/sidero-controller-manager/config/crd/bases/metal.sidero.dev_serverclasses.yaml, app/sidero-controller-manager/config/crd/bases/metal.sidero.dev_servers.yaml
Add additional printer columns
=> feat: additional printer colums

.conform.yaml, CHANGELOG.md, config/metadata/metadata.yaml, hack/release.toml
This is the official v0.5.0-alpha.0 release.
=> release(v0.5.0-alpha.0): prepare release

CHANGELOG.md
This is the official v0.4.1 release.
=> release(v0.4.1): prepare release

website/content/docs/v0.4/Guides/first-cluster.md, website/content/docs/v0.4/Overview/installation.md, website/content/docs/v0.4/Resource Configuration/environments.md, website/content/docs/v0.5/Guides/first-cluster.md
See https://github.com/talos-systems/sidero/pull/669
=> docs: update docs for upcoming Sidero 0.4.1 release

website/content/docs/v0.4/Guides/patching.md, website/content/docs/v0.4/Resource Configuration/metadata.md, website/content/docs/v0.5/Guides/patching.md, website/content/docs/v0.5/Resource Configuration/metadata.md
Add an example to show patching
=> docs: add patching examples

website/content/docs/v0.4/Resource Configuration/metadata.md, website/content/docs/v0.5/Resource Configuration/metadata.md
=> docs: fix patching examples

website/content/docs/v0.1/index.md, website/content/docs/v0.2/index.md, website/content/docs/v0.3/index.md, website/content/docs/v0.4/index.md, website/content/docs/v0.5/index.md
Updated the office hours to match Talos office hours.
=> docs: update office hours

CHANGELOG.md
This is the official v0.5.0-alpha.1 release.
=> release(v0.5.0-alpha.1): prepare release

app/sidero-controller-manager/cmd/events-manager/adapter.go
Set conditions earlier, extract part of the code from the handler into
separate functions.
=> refactor: rewrite conditions update function in the adapter

website/content/docs/v0.1/index.md, website/content/docs/v0.2/index.md, website/content/docs/v0.3/index.md, website/content/docs/v0.4/index.md, website/content/docs/v0.5/index.md
=> docs: update index.md and sync across versions

README.md, website/content/docs/v0.5/index.md
PRs: #719 #720
Co-authored-by: Steve Francis <steve.francis@siderolabs.com>
Signed-off-by: Steve Francis <steve.francis@siderolabs.com>
=> docs: update README and index page

app/sidero-controller-manager/internal/server/server.go
This PR fixes a bug where BMC secrets weren't getting moved when using
`clusterctl move`. We'll now add the "move" label to the BMC secrets
when they're created so we can be sure they come for the ride.
=> fix: add move label to BMC secrets

website/content/docs/v0.4/Overview/introduction.md, website/content/docs/v0.5/Overview/introduction.md
Improve the description of how to get started.
=> docs: update to Sidero from Talos

CHANGELOG.md
This is the official v0.5.0-alpha.2 release.
=> release(v0.5.0-alpha.2): prepare release

CHANGELOG.md
This is the official v0.5.0 release.
=> release(v0.5.0): prepare release

website/content/docs/v0.5/Overview/architecture.md, website/content/docs/v0.5/Overview/installation.md, website/content/docs/v0.5/Overview/introduction.md, website/content/docs/v0.5/Overview/resources.md, website/content/docs/v0.5/Overview/siderolink.md, website/content/docs/v0.5/Overview/whatsnew.md, website/gridsome.config.js, website/static/_redirects
I renumbered weights a bit to make it easier to insert items.
=> docs: make 0.5 docs the default, add what's new

app/caps-controller-manager/config/certmanager/certificate.yaml, app/caps-controller-manager/config/default/kustomization.yaml, app/sidero-controller-manager/config/certmanager/certificate.yaml, app/sidero-controller-manager/config/kustomization.yaml
=> chore: bump cert-manager to v1

README.md
=> docs: update README for 0.5 version compatibility

Dockerfile, Makefile
This PR updates some places in the Makefile that I missed that surfaced
after hitting the build-and-publish step with drone.
=> chore: update more registries

Makefile
Fixes iPXE prompt stuck on ARM64
Fixes: #806
Ref: https://github.com/siderolabs/pkgs/pull/440
=> fix: ipxe prompt on ARM64

Dockerfile, go.mod, go.sum, sfyra/go.mod, sfyra/go.sum
=> chore: bump dependencies

website/layouts/sitemap.xml
This PR adds the sitemap template for sidero so we can submit for better
SEO in google.
=> docs: add sitemap override

website/layouts/partials/hooks/body-end.html
This PR updates with the proper algolia info so we can actually have
search
=> docs: update algolia info

website/content/v0.1/Resource Configuration/servers.md, website/content/v0.2/Resource Configuration/servers.md, website/content/v0.3/Guides/bootstrapping.md, website/content/v0.3/Resource Configuration/servers.md, website/content/v0.4/Guides/bootstrapping.md, website/content/v0.4/Resource Configuration/servers.md, website/content/v0.5/Guides/bootstrapping.md, website/content/v0.5/Resource Configuration/servers.md, website/content/v0.6/Guides/bootstrapping.md, website/content/v0.6/Resource Configuration/servers.md
=> docs: fix spelling mistake

website/content/v0.6/Getting Started/prereq-dhcp.md
Signed-off-by: Steve Francis <steve.francis@talos-systems.com>
=> docs: edit for clarity and conciseness.

Dockerfile, sfyra/go.mod, sfyra/go.sum, sfyra/pkg/loadbalancer/loadbalancer.go
See https://github.com/siderolabs/go-loadbalancer/pull/7
=> test: integrate new controlplane loadbalancer

app/sidero-controller-manager/cmd/siderolink-manager/main.go
If wireguard endpoint is set to be a hostname and not an IP, attempt to resolve it to an IP instead of failing immediately.
Closes siderolabs/sidero#896.
Signed-off-by: Utku Ozdemir <utku.ozdemir@siderolabs.com>
=> fix: resolve wireguard endpoint to IP

Dockerfile, app/sidero-controller-manager/cmd/siderolink-manager/main.go, app/sidero-controller-manager/internal/ipxe/ipxe_server.go, sfyra/go.mod, sfyra/go.sum, sfyra/pkg/loadbalancer/loadbalancer.go
PRs backported:
- https://github.com/siderolabs/sidero/pull/864
- https://github.com/siderolabs/sidero/pull/890
- https://github.com/siderolabs/sidero/pull/898
=> backports: for 0.5.2

CHANGELOG.md, hack/release.toml
This is the official v0.5.2 release.
Signed-off-by: Utku Ozdemir <utku.ozdemir@siderolabs.com>
=> release(v0.5.2): prepare release

CHANGELOG.md, hack/release.toml
This is the official v0.5.4 release.
=> release(v0.5.4): prepare release

website/content/v0.6/Resource Configuration/servers.md
=> docs: Detail how to disable IPMI magic (re. #988)

CHANGELOG.md, hack/release.toml
This is the official v0.5.7 release.
=> release(v0.5.7): prepare release

Makefile
=> fix: use updated pkgs with fixed ipmitool

Makefile
Fixes #1013
(cherry picked from commit 18116bcabe77f1e7aa8d33b4d10cf2ff4a7cd18b)
=> backport: fix: use updated pkgs with fixed ipmitool

CHANGELOG.md, hack/release.toml
This is the official v0.5.8 release.
=> release(v0.5.8): prepare release

app/caps-controller-manager/config/default/kustomization.yaml, app/caps-controller-manager/config/default/manager_auth_proxy_patch.yaml, app/caps-controller-manager/config/prometheus/monitor.yaml, app/caps-controller-manager/config/rbac/auth_proxy_service.yaml, app/caps-controller-manager/config/rbac/kustomization.yaml, app/sidero-controller-manager/config/kustomization.yaml, app/sidero-controller-manager/config/manager_auth_proxy_patch.yaml, app/sidero-controller-manager/config/prometheus/monitor.yaml, app/sidero-controller-manager/config/rbac/auth_proxy_service.yaml, config/metadata/metadata.yaml
=> chore: add v0.6.x to metadata, fix metrics service

CHANGELOG.md
This is the official v0.6.0-beta.0 release.
=> release(v0.6.0-beta.0): prepare release

app/caps-controller-manager/config/default/manager_auth_proxy_patch.yaml, app/sidero-controller-manager/config/manager_auth_proxy_patch.yaml
=> feat: update kube-rbac-proxy to support arm64

CHANGELOG.md
This is the official v0.6.1 release.
=> release(v0.6.1): prepare release

app/sidero-controller-manager/internal/ipxe/ipxe_server.go
High Speed Networks (e.g. HPE Slingshot) with statically assigned IPs don't use DHCP services. This causes the ipxe dhcp command to fail and prevent pxe-booting from a subsequent interface. This change will allow the ipxe script to skip over these types of networks.
=> fix: handle network interfaces without dhcp during pxeboot

CHANGELOG.md, hack/release.sh, hack/release.toml
This is the official v0.6.2 release.
=> release(v0.6.2): prepare release

app/sidero-controller-manager/pkg/constants/constants.go
AgentEndpointArg and AgentMACArg values was inverted
=> fix: sidero.endpoint and sidero.mac was inverted

CHANGELOG.md, hack/release.toml
This is the official v0.6.3 release.
=> release(v0.6.3): prepare release

CHANGELOG.md, hack/release.sh
This is the official v0.6.4 release.
=> release(v0.6.4): prepare release

CHANGELOG.md, hack/release.toml
This is the official v0.6.5 release.
=> release(v0.6.5): prepare release

CHANGELOG.md, hack/release.toml
This is the official v0.6.7 release.
=> release(v0.6.7): prepare release

.conform.yaml, .github/workflows/ci.yaml, .kres.yaml
Build both amd64 and arm64 images on tag event.
=> fix(ci): arm64 container image asset

CHANGELOG.md, hack/release.toml
This is the official v0.6.10 release.
=> release(v0.6.10): prepare release
